name: update_on_push

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update github action on launch
        uses: actions/checkout@v3

      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami

      - name: set up project and generate file
        uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: mkdir web




